{{- if and .Values.custom .Values.custom.gitClone .Values.custom.gitClone.defaultAccessToken }}
apiVersion: v1
kind: Secret
metadata:
  name: jupyterhub-git-default-token
  labels:
    app: jupyterhub
    component: hub
type: Opaque
data:
  token: {{ .Values.custom.gitClone.defaultAccessToken | b64enc | quote }}
{{- end }}
