{{- if and .Values.custom .Values.custom.adminUser .Values.custom.adminUser.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: jupyterhub-admin-credentials
  labels:
    app: jupyterhub
    component: hub
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  api-token: {{ randAlphaNum 64 | b64enc | quote }}
  admin-password: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}
