apiVersion: v1
kind: Config
preferences: {}
clusters:
  - cluster:
      certificate-authority-data: 123456
      server: https://127.0.0.1:6443
    name: default
users:
  - name: aup
    user:
      client-certificate-data: 123==
      client-key-data: 123==
contexts:
  - context:
      cluster: default
      namespace: aup
      user: aup
    name: aup-context
current-context: aup-context
